'use client';

import React, { useState } from 'react';
import { X, Database, Copy, Check, Sparkles, ShieldCheck, AlertCircle } from 'lucide-react';
import { seedSupabaseSampleData } from '../lib/supabaseClient';

interface SqlSetupModalProps {
  isOpen: boolean;
  onClose: () => void;
  onRefreshData: () => Promise<void>;
}

export const SqlSetupModal: React.FC<SqlSetupModalProps> = ({
  isOpen,
  onClose,
  onRefreshData,
}) => {
  const [copied, setCopied] = useState(false);
  const [seeding, setSeeding] = useState(false);
  const [seedMessage, setSeedMessage] = useState<string | null>(null);

  const sqlScript = `-- BCAS Results Submission Progress Report System Schema
-- Table: results_submission_progress

CREATE TABLE IF NOT EXISTS results_submission_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_month VARCHAR(20) NOT NULL,
    report_year INTEGER NOT NULL,
    faculty VARCHAR(150),
    department VARCHAR(150) NOT NULL,
    program VARCHAR(200) NOT NULL,
    coordinator VARCHAR(150) NOT NULL,
    semester VARCHAR(100) NOT NULL,
    eligible_batch TEXT,
    progress_submitted BOOLEAN DEFAULT true,
    progress_not_submitted BOOLEAN DEFAULT false,
    relevant_submission_month VARCHAR(100),
    delay_submitted BOOLEAN DEFAULT false,
    delay_not_yet_submitted BOOLEAN DEFAULT false,
    remarks TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE results_submission_progress ENABLE ROW LEVEL SECURITY;

-- Set Public Row Level Security policies for client REST API operations
CREATE POLICY "Allow public select" 
    ON results_submission_progress FOR SELECT USING (true);

CREATE POLICY "Allow public insert" 
    ON results_submission_progress FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public update" 
    ON results_submission_progress FOR UPDATE USING (true);

CREATE POLICY "Allow public delete" 
    ON results_submission_progress FOR DELETE USING (true);
`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(sqlScript);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleSeed = async () => {
    setSeeding(true);
    setSeedMessage(null);
    try {
      const res = await seedSupabaseSampleData();
      setSeedMessage(res.message);
      await onRefreshData();
    } catch (err: any) {
      setSeedMessage(`Error: ${err.message}`);
    } finally {
      setSeeding(false);
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-900/70 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-2xl border border-slate-200 w-full max-w-3xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="bg-slate-900 text-white px-6 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-9 h-9 rounded-lg bg-amber-500/20 text-amber-400 border border-amber-500/30 flex items-center justify-center">
              <Database className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold">Supabase PostgreSQL Database Setup</h2>
              <p className="text-xs text-slate-400">SQL Schema Script & Seed Data Helper</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-slate-400 hover:text-white p-1.5 rounded-lg hover:bg-slate-800 transition-all"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 space-y-6 max-h-[80vh] overflow-y-auto">
          {/* Environment Variables Box */}
          <div className="bg-blue-50 border border-blue-200 rounded-xl p-4 text-xs text-blue-900 space-y-2">
            <div className="font-bold flex items-center space-x-2 text-blue-950">
              <ShieldCheck className="w-4 h-4 text-blue-600" />
              <span>Configured Supabase Credentials</span>
            </div>
            <p>Active environment variables in <code>.env.local</code>:</p>
            <div className="bg-slate-900 text-blue-300 p-3 rounded-lg font-mono text-[11px] space-y-1">
              <div>NEXT_PUBLIC_SUPABASE_URL=https://tqvsqfchxgmvjoueduyp.supabase.co</div>
              <div>NEXT_PUBLIC_SUPABASE_ANON_KEY=sb_publishable_OfikpzTmaJ4iypNI76cAKA_7xvhWwtW</div>
            </div>
          </div>

          {/* SQL Script Block */}
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold text-slate-700 uppercase tracking-wider">
                Supabase PostgreSQL SQL Script
              </h3>
              <button
                onClick={copyToClipboard}
                className="flex items-center space-x-1.5 bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold px-3 py-1.5 rounded-lg transition-all border border-slate-300"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied to Clipboard!' : 'Copy SQL Script'}</span>
              </button>
            </div>

            <pre className="bg-slate-950 text-slate-200 p-4 rounded-xl text-xs font-mono overflow-x-auto border border-slate-800 max-h-56 leading-relaxed">
              {sqlScript}
            </pre>
          </div>

          {/* Seed Data Button */}
          <div className="bg-amber-50/60 border border-amber-200 rounded-xl p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div>
                <h4 className="text-xs font-bold text-amber-950 flex items-center space-x-1.5">
                  <Sparkles className="w-4 h-4 text-amber-600" />
                  <span>Seed Realistic Sample Data</span>
                </h4>
                <p className="text-[11px] text-amber-800 mt-0.5">
                  Populates sample records across all 10 official departments with Yes/No checkboxes.
                </p>
              </div>

              <button
                onClick={handleSeed}
                disabled={seeding}
                className="flex items-center space-x-1.5 bg-amber-600 hover:bg-amber-500 text-white font-semibold text-xs px-4 py-2 rounded-xl shadow-md transition-all disabled:opacity-50"
              >
                <Database className="w-3.5 h-3.5" />
                <span>{seeding ? 'Seeding...' : 'Seed Sample Data'}</span>
              </button>
            </div>

            {seedMessage && (
              <div className="bg-white border border-amber-300 p-2.5 rounded-lg text-xs font-medium text-amber-900 flex items-center space-x-2">
                <AlertCircle className="w-4 h-4 text-amber-600" />
                <span>{seedMessage}</span>
              </div>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-50 border-t border-slate-200 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2 bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold rounded-xl"
          >
            Close Setup Guide
          </button>
        </div>
      </div>
    </div>
  );
};
